# Generated by Django 2.0.3 on 2019-01-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190116_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='İsim Soyisim')),
                ('comment_content', models.CharField(max_length=250, verbose_name='Yorumunuz')),
                ('comment_created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Oluşturma Tarihi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Article', verbose_name='Makale')),
            ],
        ),
    ]
